### PR TITLE
Task 5

### PR DESCRIPTION
**Pull request by MaheshKaramala**
Add two different Variable types and do the Add in final variable(by using Generic Variable type).

### CODE REVIEW

**Comment by MaheshKaramala** [comment]
Added Task 6
Task: Assign the values(Fruits/colors) and write in Text file or Append the line.

**Comment by MaheshKaramala** [comment]
Added Task7
Task: Assign Multiple values (Numbers) and display in the message box through index.

**Comment by MaheshKaramala** [comment]
Added Task8
Task: Assign Multiple values (Names) and display in the message box through index.

**Comment by MaheshKaramala** [comment]
Added Task 13
Task: Task: Extract the data from the vajrang.org and print the results in the excel.

**Comment by MaheshKaramala** [comment]
Added Task 15
Task: Concatenate the first name, Middle name, Last Name from the input excel and writing the results into full Name Column.

**Comment by MaheshKaramala** [comment]
Added Task 14
Task: Find the Max and Min from the list of Arrays.

**Comment by MaheshKaramala** [comment]
Added Task 16
Task: Build the Data Table and write in the Excel.

**Comment by krish952-creator** [comment]
@MaheshKaramala 
Task -5
Code verified.
Task -6
Code verified.
Task -7
Code verified.
Task -8
Code verified.
Task -13
Code verified.
Task -14
Code verified.
Task -15
Code verified.
Task -16
Code verified.

**Pull request merged**
