### PR TITLE
Task 24

### PR DESCRIPTION
**Pull request by MaheshKaramala**
Task: Assign input value (eg: UiPath Studio) , and replace the word with any other word by using Replace function.

### CODE REVIEW

**Comment by MaheshKaramala** [comment]
Added Task 26
Task: Guess the system generated random number using State Machine.

**Comment by MaheshKaramala** [comment]
Added Task 27
Task: Create a separate sequence for Add and Sub and invoke xaml files into one sequence by using Arguments(Read input values from the excel).

**Comment by MaheshKaramala** [comment]
Added Task 25
Task: Extract the information from Youtube (Automate with Uipath Channel), TItle, view and month and print the result in excel.

**Comment by krish952-creator** [comment]
@MaheshKaramala 
Task -24
Code verified.
Task -25
Code verified.
Task -26
Code verified.
Task -27
Code verified.

**Pull request merged**
