### PR TITLE
Task 20

### PR DESCRIPTION
**Pull request by MaheshKaramala**
Task: Read the excel (consists of Lower Letters), and type into website (Vajrang.org - Uppercase Task) and get the result and write into one excel.

### CODE REVIEW

**Comment by MaheshKaramala** [comment]
Added Task 17
Task: Generate Data Table from Text File and Write the created Data Table to Excel File.

**Comment by MaheshKaramala** [comment]
Added Task 18
Task: Add the data by using multiple Assign Activity (Initialize the row and add the data to rows).

**Comment by MaheshKaramala** [comment]
Added Task 19
Task: Extract the data from any website and write into Text File.

**Comment by MaheshKaramala** [comment]
Added Task 21
Task: Find the temperature of few cities and print the results into Excel.

**Comment by MaheshKaramala** [comment]
Added Task 22
Task: Read the excel (consists of Lower Letters), and type into website (Vajrang.org - Uppercase Task) (by using Add data row add the data into the excel).

**Comment by MaheshKaramala** [comment]
Added Task 23
Task: Data Manipulation: Assign set of string (eg: abcdefg), and check the (length, substring, index, Last letters and Remove).

**Comment by krish952-creator** [comment]
@MaheshKaramala 
Task -17
Code verified.
Task -18
Code verified.
Task -19
Code verified.
Task -20
Code verified.
Task -21
Code verified.
Task -22
Code verified.
Task -23
Code verified.

**Pull request merged**
